### ISSUE TITLE
error

### ISSUE THREAD

**Issue by huawuque18** [tonlabs/TON-OS-DApp-Server#10]
docker-compose/ton-node/build/Dockerfile

I suggest the RUST version be changed to 1.53.0

**Comment by huawuque18** [comment]
I used 1.51.0 and 1.53.0 to test at the same time, and found that the installation of 1.53.0 is much faster.
And 1.51.0 will be stuck for a long time.

**Comment by artemr-tl** [comment]
Updated to 1.55.0
