### ISSUE TITLE
Для перезапуска сервера нужен другой скрипт?

### ISSUE THREAD

**Issue by senitskiy** [tonlabs/TON-OS-DApp-Server#3]
Запускал https://github.com/tonlabs/TON-OS-DApp-Server .
 1) при первом deploy.sh создаёт докер-контейнеры и запускает службы;
 2) при втором deploy.sh стопит службы и удаляет директории в докер-контейнерах;
 3) при третьем и следующем deploy.sh снова удаляет директории в докер-контейнерах 
и пытается запустить службы из этих же директорий. Соответственно их не находит и падает с ошибками.

Так и задуманно или нужно написать скрипт re-deploy.sh для повторного запуска TON-OS-DApp-Server?

**Comment by artemr-tl** [comment]
Please reset your git tree before second and later deploy runs.

**Comment by artemr-tl** [comment]
Closing the issue due to no answer - please re-open it if it's still actual.
