### ISSUE TITLE
NETWORK_TYPE=main.ton.dev  error

### ISSUE THREAD

**Issue by huawuque18** [tonlabs/TON-OS-DApp-Server#7]
TON OS App server，
NETWORK_TYPE=main.ton.dev
When ton-node does not synchronize data, it prompts the above error
1616735461.529732438 TRACE [ton_node::external_db::kafka_producer] 140566803049472: Creating kafka producer (topic: blocks)...
1616735461.532777063 TRACE [ton_node::external_db::kafka_producer] 140566803049472: Kafka producer (topic: ) is DISABLED
1616735461.532810242 TRACE [ton_node::external_db::kafka_producer] 140566803049472: Creating kafka producer (topic: messages)...
1616735461.533083563 TRACE [ton_node::external_db::kafka_producer] 140566803049472: Creating kafka producer (topic: transactions)...
1616735461.533408231 TRACE [ton_node::external_db::kafka_producer] 140566803049472: Creating kafka producer (topic: accounts)...
1616735461.533640828 TRACE [ton_node::external_db::kafka_producer] 140566803049472: Creating kafka producer (topic: blocks_signatures)...
1616735461.534159416 INFO [ton_node::engine] 140566803049472: Engine::run
1616735461.534191643 INFO [ton_node::engine] 140566803049472: Creating engine...
1616735462.035297289 ERROR [ton_node] 140566803049472: Can't start node's Engine: Error("invalid type: integer 404, expected struct TonNodeGlobalConfigJson", line: 1, column: 4)

![image](https://user-images.githubusercontent.com/33893148/112612725-373ede80-8e5a-11eb-8c4b-d35d4a3b7ccc.png)

**Comment by artemr-tl** [comment]
Fixed, thanks for reporting.
Please verify.
